.gitlab-ci.yml

Upgrade mongodb in unit tests to version 4.4

---

app/app_test.go
model/message.go
tests/tests/test_connect.py

Update the websocket message to support type, session_id, status, and data

---

model/device.go
store/mongo/datastore_mongo.go
store/mongo/datastore_mongo_test.go
utils/clock.go

Add created_ts and updated_ts fields to devices' model

---

api/http/device.go
api/http/management.go
server/server.go

- Set reconnect buffer size in bytes (10 MB)
- Set reconnect interval to 1 second

Improve nats reconnection handling

---

api/http/management.go

Set session and user IDs for all proto types/messages

---

app/app.go
app/app_test.go
client/workflows/client_test.go
client/workflows/models.go

Alternative representation of auditlog entries - see mendersoftware/auditlogs#34

Change audit log structure with terminal actions and device object

---

config.yaml
tests/docker-compose.yml

Default host for workflows is mender-workflows-server

---

.golangci.yml
api/http/internal.go
api/http/management.go
api/http/management_filetransfer.go
api/http/management_filetransfer_test.go
api/http/router.go
app/app.go
app/app_test.go
app/mocks/App.go
client/workflows/models.go
docs/management_api.yml
go.mod
go.sum
model/filetransfer.go
model/filetransfer_test.go
vendor/github.com/mendersoftware/go-lib-micro/ws/filetransfer/model.go
vendor/github.com/mendersoftware/go-lib-micro/ws/protomsg.go
vendor/modules.txt

Depends on: https://github.com/mendersoftware/mender-connect/pull/17

MEN-4482, MEN-4418: implement file upload and download end-points

---

api/http/management_filetransfer.go
client/workflows/models.go

Fix: file transfer auditlogs

---

docs/management_api.yml

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

Clarify the description of the path in FileUpload

---

api/http/management_filetransfer.go

The endpoint returned 200 if it fails to parse the multipart/form-data
request, and 500 if the request is missing the closing multipart boundary.

Fix invalid responses on filetransfer upload

---

api/http/management_filetransfer.go
api/http/management_filetransfer_test.go

... or if filetransfer is disabled

Return 502 status code if the device does not implement filetransfer

---

api/http/management.go
api/http/management_test.go
app/app.go
app/app_test.go
app/mocks/App.go
client/workflows/models.go
docs/management_api.yml
model/session.go
tests/tests/test_connect.py

MEN-4474: send audit logs on port forwarding session start and stop

---

docs/devices_api.yml
docs/internal_api.yml
docs/management_api.yml

Changelog: None
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 541d4d2519f421f6717c32c7247103d60e62a6b8)

1.1.x: [docs] Use lowercase in API spec titles

---

docs/devices_api.yml
docs/internal_api.yml
docs/management_api.yml

Changelog: None
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 541d4d2519f421f6717c32c7247103d60e62a6b8)

1.0.x: [docs] Use lowercase in API spec titles

---

api/http/management_filetransfer.go

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

Delay HTTP200 to the first file chunk received.

---

docs/devices_api.yml
docs/internal_api.yml
docs/management_api.yml
tests/common.py

QA-281: make the API tags uniform with the Mender code base

---

store/mongo/recording_writer.go

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

MEN-4718 Short writes fix.

---

Makefile
tests/Dockerfile
tests/conftest.py
tests/docker-compose-acceptance.yml
tests/run.sh
tests/tests/test_connect.py

https://tracker.mender.io/browse/QA-280

QA-280: acceptance tests: use common test image

---

api/http/management.go

We need to flush the session recording in any case ConnectServeWS exits
* see https://tracker.mender.io/browse/MEN-4718?focusedCommentId=116036&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-116036
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

MEN-4718 Flush of the session recorder moved one level up

---

api/http/device.go
api/http/management.go
app/limits.go

changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 47829cbaffc48c8e32954e20f562515adc407fca)

Cherry-pick MEN-4803 to 1.0.x

---

api/http/device.go
api/http/management.go

changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 47829cbaffc48c8e32954e20f562515adc407fca)

Cherry-pick MEN-4803 to 1.1.x

---

docs/internal_api.yml

MEN-4670: fix host and scheme in internal API docs

---

client/nats/client.go
server/server.go

Enhance the nats client, add logging for reconnection events

---

LICENSE
LIC_FILES_CHKSUM.sha256
api/http/internal.go
api/http/internal_test.go
api/http/router.go
app/app.go
app/app_test.go
app/mocks/App.go
docs/internal_api.yml
store/datastore.go
store/mocks/DataStore.go
store/mongo/datastore_mongo.go
store/mongo/datastore_mongo_test.go
tests/conftest.py

Combined QA: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/447012896

Remove provisioning of tenants

---

tests/run.sh

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

chore: add the missing license file headers

---

.gitlab-ci.yml

Fix production rolling release

---

.gitlab-ci.yml

Alvaldi: don't deploy staging from a production pipeline

---

api/http/device_test.go
api/http/internal_test.go
api/http/management_filetransfer_test.go
api/http/management_test.go
api/http/router.go
api/http/status.go
api/http/status_test.go
docs/internal_api.yml
server/server.go

Changelog: Ticket
Ticket: MC-7039

feat: new internal API end-point to gracefully shutdown the service

---

app/app.go

fix: protect shutdown cancel registrations from concurrent access

---

api/http/management_filetransfer.go
api/http/management_filetransfer_test.go
api/http/router.go

This reverts commit ac23e675008548056c6fb7237fc46393f2f63f29, reversing changes made to bfa4054f22d10d68aa8d8dc432b9fdc5b93063bc.

Revert "Merge pull request #334 from alfrunes/ALV-182"

---

api/http/management_filetransfer.go
api/http/management_filetransfer_test.go
api/http/router.go

Requires: https://github.com/mendersoftware/integration/pull/2518

ALV-182: Implement filetransfer download HEAD method

---

.gitlab-ci.yml

Ticket: QA-642
Changelog: None

downstream pipeline failures workaround

---

tests/Dockerfile

chore: fix acceptance tests installing the required Python libraries

---

Dockerfile
Dockerfile.acceptance

https://tip.golang.org/doc/devel/release#go1.22.minor

Bump golang to go1.22.2
